### ISSUE TITLE
Duplicate nonce check on Server.verify_request()

### ISSUE THREAD

**Issue by edevil** [joestump/python-oauth2#129]
I've noticed that the nonce check in Server.verify_request() has been removed from the original oauth lib. Is there a reason for this?

**Comment by jaitaiwan** [comment]
Closing this as master has a fix merged today.

**Comment by philippjfr** [comment]
Sorry for coming back to this 6 years later, but can you point to the commit that actually fixed this issue? I only see the fix for [CVE-2013-4347](https://nvd.nist.gov/vuln/detail/CVE-2013-4347) here https://github.com/joestump/python-oauth2/commit/82dd2cdd4954cd7b8983d5d64c0dfd9072bf4650 but can find no reference to a fix for [CVE-2013-4346](https://nvd.nist.gov/vuln/detail/CVE-2013-4346).

**Comment by philippjfr** [comment]
Indeed looking at the `_check_signature` method on current master the `nonce` value still is not validated in any way: https://github.com/joestump/python-oauth2/blob/b94f69b1ad195513547924e380d9265133e995fa/oauth2/__init__.py#L757
